# Generated by Django 4.1.7 on 2023-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=64)),
                ('familias', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=1000)),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
    ]
