# Generated by Django 4.1.7 on 2023-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presup', '0002_remove_material_id_material_tasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='alias',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='familias',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
