# Generated by Django 4.1.7 on 2023-03-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presup', '0003_alter_material_alias_alter_material_familias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplidor',
            fields=[
                ('suplidor', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('correo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nombre_vendedor', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='familias',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
