# Generated by Django 4.1.7 on 2023-04-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presup', '0005_material_analisis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo_proyecto', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, default='', null=True)),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presup.cliente')),
            ],
        ),
    ]
