# Generated by Django 4.1.7 on 2023-04-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presup', '0008_alter_proyecto_codigo_cliente_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
